package BankingApp;


/**
* BankingApp/Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Monday, May 18, 2026 10:24:44 PM IST
*/

public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Account
