package BankingApp;


/**
* BankingApp/AccountHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Monday, May 18, 2026 10:24:44 PM IST
*/

abstract public class AccountHelper
{
  private static String  _id = "IDL:BankingApp/Account:1.0";

  public static void insert (org.omg.CORBA.Any a, BankingApp.Account that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BankingApp.Account extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BankingApp.AccountHelper.id (), "Account");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BankingApp.Account read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AccountStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BankingApp.Account value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BankingApp.Account narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BankingApp.Account)
      return (BankingApp.Account)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BankingApp._AccountStub stub = new BankingApp._AccountStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BankingApp.Account unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BankingApp.Account)
      return (BankingApp.Account)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BankingApp._AccountStub stub = new BankingApp._AccountStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
