package BankingApp;


/**
* BankingApp/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Monday, May 18, 2026 10:24:44 PM IST
*/

public interface AccountOperations 
{
  double getBalance (String accNo);
  void deposit (String accNo, double amount);
  void withdraw (String accNo, double amount) throws BankingApp.InsufficientBalance;
} // interface AccountOperations
