package BankingApp;


/**
* BankingApp/AccountPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Monday, May 18, 2026 10:24:44 PM IST
*/

public abstract class AccountPOA extends org.omg.PortableServer.Servant
 implements BankingApp.AccountOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getBalance", new java.lang.Integer (0));
    _methods.put ("deposit", new java.lang.Integer (1));
    _methods.put ("withdraw", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BankingApp/Account/getBalance
       {
         String accNo = in.read_string ();
         double $result = (double)0;
         $result = this.getBalance (accNo);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // BankingApp/Account/deposit
       {
         String accNo = in.read_string ();
         double amount = in.read_double ();
         this.deposit (accNo, amount);
         out = $rh.createReply();
         break;
       }

       case 2:  // BankingApp/Account/withdraw
       {
         try {
           String accNo = in.read_string ();
           double amount = in.read_double ();
           this.withdraw (accNo, amount);
           out = $rh.createReply();
         } catch (BankingApp.InsufficientBalance $ex) {
           out = $rh.createExceptionReply ();
           BankingApp.InsufficientBalanceHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BankingApp/Account:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Account _this() 
  {
    return AccountHelper.narrow(
    super._this_object());
  }

  public Account _this(org.omg.CORBA.ORB orb) 
  {
    return AccountHelper.narrow(
    super._this_object(orb));
  }


} // class AccountPOA
