package BankingApp;


/**
* BankingApp/InsufficientBalance.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Monday, May 18, 2026 10:24:44 PM IST
*/

public final class InsufficientBalance extends org.omg.CORBA.UserException
{
  public String msg = null;

  public InsufficientBalance ()
  {
    super(InsufficientBalanceHelper.id());
  } // ctor

  public InsufficientBalance (String _msg)
  {
    super(InsufficientBalanceHelper.id());
    msg = _msg;
  } // ctor


  public InsufficientBalance (String $reason, String _msg)
  {
    super(InsufficientBalanceHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class InsufficientBalance
